### ISSUE TITLE
LaTeX3 Error: Command '\textsi' not yet defined!

### ISSUE THREAD

**Issue by cgnieder** [cgnieder/embrac#12]
**[Original report](https://bitbucket.org/cgnieder/embrac/issue/12) by David Pesetsky (Bitbucket: [David Pesetsky](https://bitbucket.org/David Pesetsky), ).**

----------------------------------------

I have been using embrac with Lyx on MacOS 10.15, and all was well until I updated TexLive to the 2019 version.  Now compiling with embrac called reliably produces the error message:  “LaTeX3 Error: Command '\\textsi' not yet defined!”.  Removing embrac eliminates the message, as does reverting to TexLive 2018 .  I am not an expert user, so this is the limit of what I have been able to test.

**Comment by sunmy2019** [comment]
Fontspec now only defines `\texisi` if the merged shape is defined for the current font.

**Comment by cgnieder** [comment]
That should not be a problem because `embrac` checks if the macro exists before patching it and otherwise just does nothing (it writes an information to the log in that case).
