### ISSUE TITLE
Replacement for \itshape

### ISSUE THREAD

**Issue by adunning** [cgnieder/embrac#14]
Thank you for this absolutely wonderful package. I realize that it is not feasible to replace `\itshape` outright, but could the package provide its own alternative version of it? This would make it possible to apply italics with upright brackets in contexts such as headings or running heads, where it is not possible to use `\emph`.

**Comment by cgnieder** [comment]
I'm afraid that is not possible. `embrac` replaces every parenthesis or bracket by a LaTeX command. In order to do this it must read the text as argument. For larger portions of a text an environment might be a solution, though:

```latex
\documentclass{article}
\usepackage{embrac}

\NewDocumentEnvironment{emphasize}{+b}{\emph{#1}}{}

\begin{document}

\begin{emphasize}
  Text (with) parentheses and
  [brackets]
\end{emphasize}

\end{document}
```

**Comment by cgnieder** [comment]
Formatting the running header with a package such as `fancyhdr` or `scrlayer-scrpage` should allow to use `\textit`, btw.
